apiVersion: batch/v1
kind: Job
metadata:
  name: 229-robot-wait-running
  annotations:
    argocd.argoproj.io/sync-wave: "229"
  namespace: robot-shop
spec:
  template:
    spec:
      containers:
        - name: config
          image: quay.io/openshift/origin-cli:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          command:
            - /bin/sh
            - -c
            - |
              

              echo "---------------------------------------------------------------------------------"
              echo " ⏳ Wait for RobotShop being ready"
              echo "---------------------------------------------------------------------------------"

              while : ; do
                READY=$(oc get pod -n robot-shop | grep "1/1\|2/2\|3/3\|4/4"|wc -l|tr -d ' ')
                if [[  $READY  -lt '12' ]]; then
                  echo 'Deployment not completed yet.'
                  sleep 30
                else
                  break
                fi
              done
          
      serviceAccountName: openshift-argocd-admin-ai
      restartPolicy: Never
  backoffLimit: 4
