aiManager:
  core:
    aiManagerInstallOperator: false
    aiManagerInstallInstance: false
    aiManagerPullToken: <PULL_TOKEN>
  config:
    aiManagerTopology: false
    aiManagerTraining: false
    aiManagerAWX: false
    aiManagerRobotShop: false
    aiManagerLDAP: false
eventManager:
  core:
    eventManagerInstallOperator: false
    eventManagerInstallInstance: false
addons:
  TurbonomicInstall: false
  HumioInstall: false
  HumioLicense: <HUMIO_LICENSE>
  IstioInstall: false
  ELKInstall: false
activeBranch: main