{{- if .Values.aiManager.config.aiManagerTraining }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cp4waiops-aimanager-training
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: cp4waiops
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/1_cp4waiops/current/training
    repoURL: 'https://github.com/niklaushirt/aiops-install-gitops-33'
    targetRevision: 
    helm:
      valueFiles:
        - values.yaml
  project: cp4waiops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      #- Validate=false
      - SkipDryRunOnMissingResource=true
      #- FailOnSharedResource=true
      #- CreateNamespace=true
      - ApplyOutOfSyncOnly=true

{{- end }}
