{{- if .Values.aiManager.core.aiManagerInstallOperator }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cp4waiops-aimanageroperator
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: cp4waiops
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/1_cp4waiops/current/aimanageroperator
    repoURL: 'https://github.com/niklaushirt/aiops-install-gitops-33'
    targetRevision: 
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: spec.dockerPassword
          value: >-
            {{ .Values.aiManager.core.aiManagerPullToken }}
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - SkipDryRunOnMissingResource=true
      - FailOnSharedResource=true
      #- CreateNamespace=true
      - ApplyOutOfSyncOnly=true

{{- end }}
