---
apiVersion: batch/v1
kind: Job
metadata:
  name: 272-ai-training-load-snow-indexes
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "272"
spec:
  template:
    spec:
      containers:
        - name: load
          image: niklaushirt/cp4waiops-tools:1.3
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          command:
            - /bin/sh
            - -c
            - |
              #!/bin/bash
              
              export AWX_REPO=https://github.com/niklaushirt/awx-waiops-trainingdata.git
              git clone $AWX_REPO
              cd awx-waiops-trainingdata
              ./training/robotshop-load-snow-for-training.sh
          env:
            - name: INDEX_OVERWRITE
              value : "false"
            - name: VERSION
              value : "3.3"
      restartPolicy: Never

  backoffLimit: 4
