---
apiVersion: batch/v1
kind: Job
metadata:
  name: 273-ai-training-wait-load
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "273"
spec:
  template:
    spec:
      containers:
        - name: load
          image: niklaushirt/cp4waiops-tools:1.3
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          command:
            - /bin/sh
            - -c
            - |

              echo "---------------------------------------------------------------------------------"
              echo " 📥 Wait for metric load"
              echo "---------------------------------------------------------------------------------"

              while : ; do
                    READY=$(oc get jobs -n default load-metric-cassandra)
                    if [[ ! $READY  =~ "1/1" ]]; then
                          echo "        Load Job not completed. Waiting 30 seconds"
                          sleep 30
                    else
                          break
                    fi
              done
              echo "      ✅ OK"

              oc delete job  -n default --ignore-not-found 272-ai-training-load-metric-indexes
              oc delete pod  -n default --ignore-not-found $(oc get po -n default|grep load-snow-indexes|awk '{print$1}')

              echo "---------------------------------------------------------------------------------"
              echo " 📥 Wait for SNOW load"
              echo "---------------------------------------------------------------------------------"
              while : ; do
                    READY=$(oc get jobs -n default load-snow-indexes)
                    if [[ ! $READY  =~ "1/1" ]]; then
                          echo "        Load Job not completed. Waiting 30 seconds"
                          sleep 30
                    else
                          break
                    fi
              done
              echo "      ✅ OK"

              oc delete job  -n default --ignore-not-found 272-ai-training-load-mesnowtric-indexes
              oc delete pod  -n default --ignore-not-found $(oc get po -n default|grep load-snow-indexes|awk '{print$1}')

              echo "---------------------------------------------------------------------------------"
              echo " 📥 Wait for Logs load"
              echo "---------------------------------------------------------------------------------"
              while : ; do
                    READY=$(oc get jobs -n default load-log-indexes)
                    if [[ ! $READY  =~ "1/1" ]]; then
                          echo "        Load Job not completed. Waiting 30 seconds"
                          sleep 30
                    else
                          break
                    fi
              done
              echo "      ✅ OK"

              oc delete job  -n default --ignore-not-found 272-ai-training-load-log-indexes
              oc delete pod  -n default --ignore-not-found $(oc get po -n default|grep load-log-indexes|awk '{print$1}')

              echo "---------------------------------------------------------------------------------"
              echo " ✅ DONE"
              echo "---------------------------------------------------------------------------------"

          env:
            - name: INDEX_OVERWRITE
              value : "false"
            - name: VERSION
              value : "3.3"
      restartPolicy: Never

  backoffLimit: 4
