apiVersion: batch/v1
kind: Job
metadata:
  name: 129-ai-launch-robot-shop-install
  annotations:
    argocd.argoproj.io/sync-wave: "129"
    argocd.argoproj.io/sync-options: Replace=true
  namespace: {{.Values.spec.aiManager.namespace}}
spec:
  template:
    spec:
      containers:
        - name: config
          image: quay.io/openshift/origin-cli:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          command:
            - /bin/sh
            - -c
            - |


              echo "---------------------------------------------------------------------------------"
              echo " 🚀 Launch Installation of AI Manager and Robot Shop"
              echo "---------------------------------------------------------------------------------"

              oc patch applications.argoproj.io -n openshift-gitops installer --type=json -p='[{"op": "add", "path": "/spec/source/helm/parameters/-", "value":{"name":"aiManager.config.aiManagerRobotShop","value":"true"}}]'

      restartPolicy: Never
      serviceAccountName: openshift-argocd-admin-ai
  backoffLimit: 4
