apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: noi-operator-group
  namespace: {{.Values.spec.eventManager.namespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "110"
spec:
  targetNamespaces:
    - {{.Values.spec.eventManager.namespace}}
