apiVersion: batch/v1
kind: Job
metadata:
  name: 100-argo-cp4waiops-image-pull-secret
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  namespace: {{.Values.spec.aiManager.namespace}}
spec:
  template:
    spec:
      containers:
        - name: config
          image: quay.io/openshift/origin-cli:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "64Mi"
              cpu: "200m"
          command:
            - /bin/sh
            - -c
            - |
              echo "---------------------------------------------------------------------------------"
              echo " 💊 Patching Pull Secrets"
              echo "---------------------------------------------------------------------------------"

              while : ; do
                READY=$(oc get -n openshift-marketplace serviceaccount ibm-operator-catalog --ignore-not-found)
                if [[ ! $READY  =~ 'ibm-operator-catalog' ]]; then
                  echo '"ibm-operator-catalog" is not ready yet.'
                  sleep 10
                else
                  break
                fi
              done

              oc patch -n openshift-marketplace serviceaccount ibm-operator-catalog -p '{"imagePullSecrets": [{"name": "ibm-entitlement-key"}]}'
              
              oc patch -n openshift-marketplace serviceaccount default -p '{"imagePullSecrets": [{"name": "ibm-entitlement-key"}]}'


      restartPolicy: Never
      serviceAccountName: openshift-argocd-admin-ai
  backoffLimit: 4